version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "0xSoul24"
    assignees:
      - "0xSoul24"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "gradle"
