name: ${name}
version: ${version}
description: Immersive and lore friendly extensions for vanilla minecraft

authors: [oddlama]
website: ${url}

depend: [ProtocolLib]
softdepend: [dynmap]

main: imex.Main
database: false

api-version: 1.16
load: STARTUP
