name: ${name}
version: ${version}
description: Immersive and lore friendly extensions for vanilla minecraft

authors: [oddlama]
website: 'https://github.com/oddlama/vane'

depend: [ProtocolLib]
softdepend: [dynmap]

main: org.oddlama.vane.core.Core
database: false

api-version: 1.16
load: STARTUP
