name: ${name}
version: ${version}
description: Bedtime module for vane

authors: [oddlama]
website: 'https://github.com/oddlama/vane'

depend: [vane-core]

main: org.oddlama.vane.bedtime.Bedtime
database: false

api-version: 1.16
load: STARTUP
