name: ${name}
version: ${version}
description: Bedtime module for imex

authors: [oddlama]
website: 'https://github.com/oddlama/imex'

depend: [imex-core]

main: org.oddlama.imex.bedtime.Main
database: false

api-version: 1.16
load: STARTUP
