name: ${name}
version: ${version}
description: Enhancements module for vane

authors: [oddlama]
website: 'https://github.com/oddlama/vane'

depend: [vane-core]

main: org.oddlama.vane.enhancements.Enhancements
database: false

api-version: 1.16
load: STARTUP
