[[categories]]
id = "gameplay"
title = "Gameplay"

[[categories]]
id = "custom_items"
title = "Custom Items"

[[categories]]
id = "enchantments"
title = "Enchantments"

[[categories]]
id = "mechanics"
title = "Mechanics"

[[categories]]
id = "administrative"
title = "Administrative Features"
